image: Visual Studio 2017 Preview

version: '0.7.0.{build}'

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

branches:
  only:
    - dev
    - master

# clone directory
clone_folder: c:\projects\djvunet

# Force git at least 1 commit depth repo which is equivalent to zip download
# but has git repo with last commit - it allows to retrieve commit hash
# during build and using it for assembly attributes initialization
# clone_depth: 10

test:
  categories:
    except:
      - Skip

matrix:
  fast_finish: false

# Maximum number of concurrent jobs for the project
max_jobs: 4

cache:
#    - packages -> **\packages.config
#    - artifacts -> artifacts.sha256

# environment variables
environment:
    TargetFramework: net472

############################################################################
#
#  BUILD SEQUENCE
#
############################################################################

init:
    - cmd: git config --global core.autocrlf false

install:
    - cmd: cd c:\projects\djvunet
    - cmd: if exist DjvuLibre\ rd /s /q DjvuLibre
    - cmd: if exist artifacts\ rd /s /q artifacts
    - cmd: git clone https://github.com/DjvuNet/DjVuLibre.git
    - cmd: powershell -NoProfile DjvuNet.Build/Get-Tools.ps1 https://github.com/DjvuNet/artifacts/releases/download/v0.7.0.11/Tools.zip Tools.zip Tools BuildTools
    - cmd: cd Tools
    - cmd: dir
    - cmd: cd ..
    - cmd: powershell -NoProfile DjvuNet.Build/Get-Tools.ps1 https://github.com/DjvuNet/artifacts/releases/download/v0.7.0.11/deps.zip deps.zip deps NativeDeps
    - cmd: cd deps
    - cmd: dir
    - cmd: cd ..
    - appveyor DownloadFile https://github.com/DjvuNet/artifacts/releases/download/v0.7.0.11/artifacts.zip
    - cmd: 7z x -oartifacts artifacts.zip

before_build:
    - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - appveyor-retry nuget restore c:\projects\djvunet\DjvuNet.sln -DisableParallelProcessing  -verbosity detailed

#build:
#    project: DjvuNet.sln
#    verbosity: detailed

build_script:
    - msbuild DjvuNet.sln /v:detailed /m /p:TargetFramework=net472 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
